### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by jorisbontje** [LearnersGuild/github-clubhouse#3]
with github-clubhouse@0.2.0 on OSX
github token and clubhouse tokens previously saved in `~/.github-clubhouse`

```
$ gh2ch https://github.com/EtherCasts/state-of-the-dapps/issues/24 state-of-the-dapps
TypeError: Cannot read property 'id' of undefined
    at _callee$ (/Users/mids/.node/lib/node_modules/github-clubhouse/lib/index.js:46:43)
    at tryCatch (/Users/mids/.node/lib/node_modules/github-clubhouse/node_modules/regenerator-runtime/runtime.js:64:40)
    at Generator.invoke [as _invoke] (/Users/mids/.node/lib/node_modules/github-clubhouse/node_modules/regenerator-runtime/runtime.js:355:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/mids/.node/lib/node_modules/github-clubhouse/node_modules/regenerator-runtime/runtime.js:116:21)
    at step (/Users/mids/.node/lib/node_modules/github-clubhouse/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/mids/.node/lib/node_modules/github-clubhouse/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
```

**Comment by jorisbontje** [comment]
Turns out this is because I used the name `state-of-the-dapps` from the URL, rather than the human name `State of the Dapps` (which includes spaces). After using the human name it worked.
