### ISSUE TITLE
The NPM module throws an error

### ISSUE THREAD

**Issue by asitemade4u** [LearnersGuild/github-clubhouse#5]
Here is the error message when trying to import a particular issue from my private repo:

```
TypeError: Cannot read property 'id' of undefined
    at _callee$ (/home/stsinc/.npm-packages/lib/node_modules/github-clubhouse/lib/index.js:46:43)
    at tryCatch (/home/stsinc/.npm-packages/lib/node_modules/github-clubhouse/node_modules/regenerator-runtime/runtime.js:64:40)
    at Generator.invoke [as _invoke] (/home/stsinc/.npm-packages/lib/node_modules/github-clubhouse/node_modules/regenerator-runtime/runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (/home/stsinc/.npm-packages/lib/node_modules/github-clubhouse/node_modules/regenerator-runtime/runtime.js:116:21)
    at step (/home/stsinc/.npm-packages/lib/node_modules/github-clubhouse/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/stsinc/.npm-packages/lib/node_modules/github-clubhouse/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

What am I doing wrong?
NB. I have installed gh2ch globally.
Thank you.

**Comment by ctolkien** [comment]
Same issue here....

**Comment by jeffreywescott** [comment]
This issue would occur because of [this line](https://github.com/LearnersGuild/github-clubhouse/blob/master/src/index.js#L14).

This means that whatever you're passing for `CLUBHOUSE_PROJECT_NAME` is not found. If your clubhouse project name has whitespace in it, be sure to wrap quotes around that in the project name, for example:

```
gh2ch https://github.com/LearnersGuild/github-clubhouse "this will succeed"
```

... vs. ...

```
gh2ch https://github.com/LearnersGuild/github-clubhouse this will fail
```

If this is _not_ your issue, please reopen this bug with the exact command you're trying. Thanks!

**Comment by ctolkien** [comment]
That wasn't my issue - I tried wrapping in quotes, etc to no avail. I ended up writing my own importer:

https://github.com/ctolkien/GitHub2Clubhouse
